on: [push]
jobs:
  build_and_static_analysis:
    runs-on: ubuntu-latest
    container:
      image: artfulbytes/msp430-gcc-9.3.1.11:latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - run: make format && git diff --quiet
      - run: make cppcheck
      - run: TOOLS_PATH=/home/ubuntu/dev/tools make HW=NSUMO
      - run: TOOLS_PATH=/home/ubuntu/dev/tools make HW=LAUNCHPAD
      - run: TOOLS_PATH=/home/ubuntu/dev/tools tools/build_tests.sh
